### ISSUE TITLE
Regelmäßige Fehlermeldung 

### ISSUE THREAD

**Issue by Claus1985** [rde-master/ioBroker.todoist2#84]
**Describe the bug**  
Seit ein paar Tagen erhalte ich täglich mehrmals folgende Fehlermeldung (bis zu 8 mal am Tag):

`2022-09-18 08:00:04.906 | warn | {"message":"Request failed with status code 503","name":"Error","stack":"Error: Request failed with status code 503\n at createError (/opt/iobroker/node_modules/iobroker.todoist2/node_modules/axios/lib/core/createError.js:16:15)\n at settle (/opt/iobroker/node_modules/iobroker.todoist2/node_modules/axios/lib/core/settle.js:17:12)\n at IncomingMessage.handleStreamEnd (/opt/iobroker/node_modules/iobroker.todoist2/node_modules/axios/lib/adapters/http.js:293:11)\n at IncomingMessage.emit (events.js:412:35)\n at endReadableNT (internal/streams/readable.js:1333:12)\n at processTicksAndRejections (internal/process/task_queues.js:82:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"headers":{"Accept":"application/json, text/plain, */*","Authorization":"Bearer d2a6aa5c0f250d70b9d30fc6bd715d76ee37fbf6","User-Agent":"axios/0.24.0"},"method":"get","baseURL":"https://api.todoist.com","url":"/rest/v1/projects","responseType":"json"},"status":503}
-- | -- | --
todoist2.0 | 2022-09-18 08:00:04.876 | warn | received error 503 response from todoist with content: "Service Unavailable\n"`

Woran kann das liegen und was muss ich tun um das zu ändern?

Vielen Dank!

**Versions:**  
 - Adapter version: <0.9>
 - Node version: <14.2>
 - Operating system: <raspbian buster>

**Comment by Ullulaki** [comment]
Same here! Hast du eventuelle Auswirkungen bzw. Probleme bei der Synchronisierung feststellen können oder läuft bei dir trotzdem alles "normal"?

**Comment by Claus1985** [comment]
Funktioniert bisher wie gehabt einwandfrei. Ist eigentlich nur nervig da das dauernd im log auftaucht.
